# Generated by Django 4.0.3 on 2024-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
