# Generated by Django 4.0.3 on 2024-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_app', '0002_alter_player_matches_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='strike_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
